[linux]
ubuntu ansible_host=192.168.18.132
opensuse ansible_host=192.168.18.135

[linux:vars]
ansible_user=amir

[kuber]
master ansible_host=192.168.18.136
worker ansible_host=192.168.18.137

[kuber:vars]
ansible_user=amir
ansible_password=123
ansible_become=true
ansible_become_password=Amir@8013
ansible_become_method=sudo
