- name: Ensure report directory exists
  ansible.builtin.file:
    path: "{{ report_output_dir }}"
    state: directory
    mode: "0755"
  delegate_to: localhost

- name: Generate infrastructure report
  ansible.builtin.template:
    src: report.txt.j2
    mode: "0644"
    dest: "{{ report_output_dir }}/{{ inventory_hostname }}_{{ ansible_date_time.date }}_{{ ansible_date_time.time }}.txt"
  delegate_to: localhost
