---
# ============================================================================
# Initialize Kubernetes facts
# ============================================================================

- name: Initialize Kubernetes facts
  ansible.builtin.set_fact:
    kubernetes:
      installed: false
      distribution: "Not Installed"
      version: ""
      raw_version: ""
      node_roles: []
      components: []

# ============================================================================
# Gather system information
# ============================================================================

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Check if RKE2 binary exists
  ansible.builtin.stat:
    path: /usr/local/bin/rke2
  register: rke2_binary

- name: Check if Docker service exists
  ansible.builtin.set_fact:
    docker_exists: "{{ 'docker.service' in ansible_facts.services }}"

- name: Check if kubelet systemd service exists
  ansible.builtin.set_fact:
    kubelet_service_exists: "{{ 'kubelet.service' in ansible_facts.services }}"

- name: Check if kubelet Docker container exists
  ansible.builtin.command: docker inspect kubelet
  register: kubelet_container
  failed_when: false
  changed_when: false
  when: docker_exists

# ============================================================================
# Detect whether Kubernetes exists
# ============================================================================

- name: Determine if Kubernetes is installed
  ansible.builtin.set_fact:
    kubernetes: >-
      {{
        kubernetes | combine({
          'installed':
            kubelet_service_exists or
            (
              docker_exists and
              kubelet_container.rc == 0
            ) or
            rke2_binary.stat.exists and
            (
              'rke2-server.service' in ansible_facts.services or
              'rke2-agent.service' in ansible_facts.services
            )
        })
      }}

# ============================================================================
# Detect distribution
# ============================================================================

- name: Detect RKE2
  ansible.builtin.set_fact:
    kubernetes: >-
      {{
        kubernetes | combine({
          'distribution': 'RKE2'
        })
      }}
  when:
    - kubernetes.installed
    - rke2_binary.stat.exists
    - "'rke2-server.service' in ansible_facts.services or
       'rke2-agent.service' in ansible_facts.services"

- name: Detect RKE1
  ansible.builtin.set_fact:
    kubernetes: >-
      {{
        kubernetes | combine({
          'distribution': 'RKE1'
        })
      }}
  when:
    - kubernetes.installed
    - docker_exists
    - not rke2_binary.stat.exists

- name: Detect unknown Kubernetes distribution
  ansible.builtin.set_fact:
    kubernetes: >-
      {{
        kubernetes | combine({
          'distribution': 'Unknown'
        })
      }}
  when:
    - kubernetes.installed
    - kubernetes.distribution == "Not Installed"

- name: test
  debug:
    var: kubernetes